#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the caesarCipher function below.
def caesarCipher(s, k):
    final=''
    #print(ord('A'))  65
    #print(ord('a')) 97 
    #print(ord('Z')) 90
    #print(ord('z')) 122

    for i in s:
        if((ord(i)>=65 and ord(i)<=90) or (ord(i)>=97 and ord(i)<=122)):
            if(i.isupper()):
                final+=chr(((ord(i)+k-65)%26)+65)
            else:
                final+=chr(((ord(i)+k-97)%26)+97)
        else:
            final+=i
    
    return final


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    k = int(input())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
